package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

/**
 * TEntityXreferenceId generated by hbm2java
 */
public class TEntityXreferenceId
    implements java.io.Serializable {

    private int entityId;

    private String xrefType;

    public TEntityXreferenceId() {
    }

    public TEntityXreferenceId(int entityId, String xrefType) {
        this.entityId = entityId;
        this.xrefType = xrefType;
    }

    public int getEntityId() {

        return this.entityId;
    }

    public void setEntityId(int entityId) {

        this.entityId = entityId;
    }

    public String getXrefType() {

        return this.xrefType;
    }

    public void setXrefType(String xrefType) {

        this.xrefType = xrefType;
    }

    public boolean equals(Object other) {

        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TEntityXreferenceId))
            return false;
        TEntityXreferenceId castOther = (TEntityXreferenceId) other;

        return (this.getEntityId() == castOther.getEntityId())
            && ((this.getXrefType() == castOther.getXrefType())
                || (this.getXrefType() != null
                    && castOther.getXrefType() != null
                    && this.getXrefType().equals(castOther.getXrefType())));
    }

    public int hashCode() {

        int result = 17;

        result = 37 * result + this.getEntityId();
        result = 37 * result
            + (getXrefType() == null ? 0 : this.getXrefType().hashCode());
        return result;
    }

}
