package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * THoldingMain generated by hbm2java
 */
public class THoldingMain
    implements java.io.Serializable {

    private int entityId;

    private String holdingType;

    private String securityId;

    private Integer noOfShares;

    private Byte sharePrice;

    private Short expAmount;

    private Integer tna;

    private Byte tnaPct;

    private Date lastModDate;

    public THoldingMain() {
    }

    public THoldingMain(int entityId) {
        this.entityId = entityId;
    }

    public THoldingMain(int entityId, String holdingType, String securityId,
                        Integer noOfShares, Byte sharePrice, Short expAmount,
                        Integer tna, Byte tnaPct, Date lastModDate) {
        this.entityId = entityId;
        this.holdingType = holdingType;
        this.securityId = securityId;
        this.noOfShares = noOfShares;
        this.sharePrice = sharePrice;
        this.expAmount = expAmount;
        this.tna = tna;
        this.tnaPct = tnaPct;
        this.lastModDate = lastModDate;
    }

    public int getEntityId() {

        return this.entityId;
    }

    public void setEntityId(int entityId) {

        this.entityId = entityId;
    }

    public String getHoldingType() {

        return this.holdingType;
    }

    public void setHoldingType(String holdingType) {

        this.holdingType = holdingType;
    }

    public String getSecurityId() {

        return this.securityId;
    }

    public void setSecurityId(String securityId) {

        this.securityId = securityId;
    }

    public Integer getNoOfShares() {

        return this.noOfShares;
    }

    public void setNoOfShares(Integer noOfShares) {

        this.noOfShares = noOfShares;
    }

    public Byte getSharePrice() {

        return this.sharePrice;
    }

    public void setSharePrice(Byte sharePrice) {

        this.sharePrice = sharePrice;
    }

    public Short getExpAmount() {

        return this.expAmount;
    }

    public void setExpAmount(Short expAmount) {

        this.expAmount = expAmount;
    }

    public Integer getTna() {

        return this.tna;
    }

    public void setTna(Integer tna) {

        this.tna = tna;
    }

    public Byte getTnaPct() {

        return this.tnaPct;
    }

    public void setTnaPct(Byte tnaPct) {

        this.tnaPct = tnaPct;
    }

    public Date getLastModDate() {

        return this.lastModDate;
    }

    public void setLastModDate(Date lastModDate) {

        this.lastModDate = lastModDate;
    }

}
