package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TIamProfileRole generated by hbm2java
 */
public class TIamProfileRole
    implements java.io.Serializable {

    private TIamProfileRoleId id;

    private TIamProfile TIamProfile;

    private TIamRole TIamRole;

    private Date lastModDate;

    private String lastModBy;

    public TIamProfileRole() {
    }

    public TIamProfileRole(TIamProfileRoleId id, TIamProfile TIamProfile,
                           TIamRole TIamRole) {
        this.id = id;
        this.TIamProfile = TIamProfile;
        this.TIamRole = TIamRole;
    }

    public TIamProfileRole(TIamProfileRoleId id, TIamProfile TIamProfile,
                           TIamRole TIamRole, Date lastModDate,
                           String lastModBy) {
        this.id = id;
        this.TIamProfile = TIamProfile;
        this.TIamRole = TIamRole;
        this.lastModDate = lastModDate;
        this.lastModBy = lastModBy;
    }

    public TIamProfileRoleId getId() {

        return this.id;
    }

    public void setId(TIamProfileRoleId id) {

        this.id = id;
    }

    public TIamProfile getTIamProfile() {

        return this.TIamProfile;
    }

    public void setTIamProfile(TIamProfile TIamProfile) {

        this.TIamProfile = TIamProfile;
    }

    public TIamRole getTIamRole() {

        return this.TIamRole;
    }

    public void setTIamRole(TIamRole TIamRole) {

        this.TIamRole = TIamRole;
    }

    public Date getLastModDate() {

        return this.lastModDate;
    }

    public void setLastModDate(Date lastModDate) {

        this.lastModDate = lastModDate;
    }

    public String getLastModBy() {

        return this.lastModBy;
    }

    public void setLastModBy(String lastModBy) {

        this.lastModBy = lastModBy;
    }

}
