package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

/**
 * TIamProfileRoleId generated by hbm2java
 */
public class TIamProfileRoleId
    implements java.io.Serializable {

    private int profileId;

    private int roleId;

    public TIamProfileRoleId() {
    }

    public TIamProfileRoleId(int profileId, int roleId) {
        this.profileId = profileId;
        this.roleId = roleId;
    }

    public int getProfileId() {

        return this.profileId;
    }

    public void setProfileId(int profileId) {

        this.profileId = profileId;
    }

    public int getRoleId() {

        return this.roleId;
    }

    public void setRoleId(int roleId) {

        this.roleId = roleId;
    }

    public boolean equals(Object other) {

        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TIamProfileRoleId))
            return false;
        TIamProfileRoleId castOther = (TIamProfileRoleId) other;

        return (this.getProfileId() == castOther.getProfileId())
            && (this.getRoleId() == castOther.getRoleId());
    }

    public int hashCode() {

        int result = 17;

        result = 37 * result + this.getProfileId();
        result = 37 * result + this.getRoleId();
        return result;
    }

}
