package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TIamProfile generated by hbm2java
 */
public class TIamProfile
    implements java.io.Serializable {

    private int userId;

    private String userFirstName;

    private String userLastName;

    private Date createdOn;

    private String createdBy;

    private Date updatedOn;

    private String updatedBy;

    private Set<TIamProfileRole> TIamProfileRoles =
        new HashSet<TIamProfileRole>(0);

    public TIamProfile() {
    }

    public TIamProfile(int userId, String userFirstName, String userLastName) {
        this.userId = userId;
        this.userFirstName = userFirstName;
        this.userLastName = userLastName;
    }

    public TIamProfile(int userId, String userFirstName, String userLastName,
                       Date createdOn, String createdBy, Date updatedOn,
                       String updatedBy,
                       Set<TIamProfileRole> TIamProfileRoles) {
        this.userId = userId;
        this.userFirstName = userFirstName;
        this.userLastName = userLastName;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedOn = updatedOn;
        this.updatedBy = updatedBy;
        this.TIamProfileRoles = TIamProfileRoles;
    }

    public int getUserId() {

        return this.userId;
    }

    public void setUserId(int userId) {

        this.userId = userId;
    }

    public String getUserFirstName() {

        return this.userFirstName;
    }

    public void setUserFirstName(String userFirstName) {

        this.userFirstName = userFirstName;
    }

    public String getUserLastName() {

        return this.userLastName;
    }

    public void setUserLastName(String userLastName) {

        this.userLastName = userLastName;
    }

    public Date getCreatedOn() {

        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {

        this.createdOn = createdOn;
    }

    public String getCreatedBy() {

        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {

        this.createdBy = createdBy;
    }

    public Date getUpdatedOn() {

        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {

        this.updatedOn = updatedOn;
    }

    public String getUpdatedBy() {

        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {

        this.updatedBy = updatedBy;
    }

    public Set<TIamProfileRole> getTIamProfileRoles() {

        return this.TIamProfileRoles;
    }

    public void setTIamProfileRoles(Set<TIamProfileRole> TIamProfileRoles) {

        this.TIamProfileRoles = TIamProfileRoles;
    }

}
