package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TIamRole generated by hbm2java
 */
public class TIamRole
    implements java.io.Serializable {

    private int roleId;

    private String roleName;

    private String roleDescription;

    private Date lastModDate;

    private String lastModBy;

    private Set<TIamProfileRole> TIamProfileRoles =
        new HashSet<TIamProfileRole>(0);

    public TIamRole() {
    }

    public TIamRole(int roleId, String roleName, String roleDescription) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.roleDescription = roleDescription;
    }

    public TIamRole(int roleId, String roleName, String roleDescription,
                    Date lastModDate, String lastModBy,
                    Set<TIamProfileRole> TIamProfileRoles) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.roleDescription = roleDescription;
        this.lastModDate = lastModDate;
        this.lastModBy = lastModBy;
        this.TIamProfileRoles = TIamProfileRoles;
    }

    public int getRoleId() {

        return this.roleId;
    }

    public void setRoleId(int roleId) {

        this.roleId = roleId;
    }

    public String getRoleName() {

        return this.roleName;
    }

    public void setRoleName(String roleName) {

        this.roleName = roleName;
    }

    public String getRoleDescription() {

        return this.roleDescription;
    }

    public void setRoleDescription(String roleDescription) {

        this.roleDescription = roleDescription;
    }

    public Date getLastModDate() {

        return this.lastModDate;
    }

    public void setLastModDate(Date lastModDate) {

        this.lastModDate = lastModDate;
    }

    public String getLastModBy() {

        return this.lastModBy;
    }

    public void setLastModBy(String lastModBy) {

        this.lastModBy = lastModBy;
    }

    public Set<TIamProfileRole> getTIamProfileRoles() {

        return this.TIamProfileRoles;
    }

    public void setTIamProfileRoles(Set<TIamProfileRole> TIamProfileRoles) {

        this.TIamProfileRoles = TIamProfileRoles;
    }

}
