package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

/**
 * TReportTemplate generated by hbm2java
 */
public class TReportTemplate
    implements java.io.Serializable {

    private TReportTemplateId id;

    private String rptTemplateDescription;

    public TReportTemplate() {
    }

    public TReportTemplate(TReportTemplateId id) {
        this.id = id;
    }

    public TReportTemplate(TReportTemplateId id,
                           String rptTemplateDescription) {
        this.id = id;
        this.rptTemplateDescription = rptTemplateDescription;
    }

    public TReportTemplateId getId() {

        return this.id;
    }

    public void setId(TReportTemplateId id) {

        this.id = id;
    }

    public String getRptTemplateDescription() {

        return this.rptTemplateDescription;
    }

    public void setRptTemplateDescription(String rptTemplateDescription) {

        this.rptTemplateDescription = rptTemplateDescription;
    }

}
