package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

/**
 * TReportTemplateElementsId generated by hbm2java
 */
public class TReportTemplateElementsId
    implements java.io.Serializable {

    private String rptTemplate;

    private String dataElementGrp;

    private String dataElement;

    public TReportTemplateElementsId() {
    }

    public TReportTemplateElementsId(String rptTemplate, String dataElementGrp,
                                     String dataElement) {
        this.rptTemplate = rptTemplate;
        this.dataElementGrp = dataElementGrp;
        this.dataElement = dataElement;
    }

    public String getRptTemplate() {

        return this.rptTemplate;
    }

    public void setRptTemplate(String rptTemplate) {

        this.rptTemplate = rptTemplate;
    }

    public String getDataElementGrp() {

        return this.dataElementGrp;
    }

    public void setDataElementGrp(String dataElementGrp) {

        this.dataElementGrp = dataElementGrp;
    }

    public String getDataElement() {

        return this.dataElement;
    }

    public void setDataElement(String dataElement) {

        this.dataElement = dataElement;
    }

    public boolean equals(Object other) {

        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TReportTemplateElementsId))
            return false;
        TReportTemplateElementsId castOther = (TReportTemplateElementsId) other;

        return ((this.getRptTemplate() == castOther.getRptTemplate())
            || (this.getRptTemplate() != null
                && castOther.getRptTemplate() != null
                && this.getRptTemplate().equals(castOther.getRptTemplate())))
            && ((this.getDataElementGrp() == castOther.getDataElementGrp())
                || (this.getDataElementGrp() != null
                    && castOther.getDataElementGrp() != null
                    && this.getDataElementGrp()
                        .equals(castOther.getDataElementGrp())))
            && ((this.getDataElement() == castOther.getDataElement())
                || (this.getDataElement() != null
                    && castOther.getDataElement() != null && this
                        .getDataElement().equals(castOther.getDataElement())));
    }

    public int hashCode() {

        int result = 17;

        result = 37 * result
            + (getRptTemplate() == null ? 0 : this.getRptTemplate().hashCode());
        result = 37 * result + (getDataElementGrp() == null ? 0
            : this.getDataElementGrp().hashCode());
        result = 37 * result
            + (getDataElement() == null ? 0 : this.getDataElement().hashCode());
        return result;
    }

}
