package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TReportEntity generated by hbm2java
 */
public class TReportEntity
    implements java.io.Serializable {

    private TReportEntityId id;

    private String rptTemplate;

    private Date startDate;

    private Date expiryDate;

    private Date lastModDate;

    private String lastModBy;

    public TReportEntity() {
    }

    public TReportEntity(TReportEntityId id) {
        this.id = id;
    }

    public TReportEntity(TReportEntityId id, String rptTemplate, Date startDate,
                         Date expiryDate, Date lastModDate, String lastModBy) {
        this.id = id;
        this.rptTemplate = rptTemplate;
        this.startDate = startDate;
        this.expiryDate = expiryDate;
        this.lastModDate = lastModDate;
        this.lastModBy = lastModBy;
    }

    public TReportEntityId getId() {

        return this.id;
    }

    public void setId(TReportEntityId id) {

        this.id = id;
    }

    public String getRptTemplate() {

        return this.rptTemplate;
    }

    public void setRptTemplate(String rptTemplate) {

        this.rptTemplate = rptTemplate;
    }

    public Date getStartDate() {

        return this.startDate;
    }

    public void setStartDate(Date startDate) {

        this.startDate = startDate;
    }

    public Date getExpiryDate() {

        return this.expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {

        this.expiryDate = expiryDate;
    }

    public Date getLastModDate() {

        return this.lastModDate;
    }

    public void setLastModDate(Date lastModDate) {

        this.lastModDate = lastModDate;
    }

    public String getLastModBy() {

        return this.lastModBy;
    }

    public void setLastModBy(String lastModBy) {

        this.lastModBy = lastModBy;
    }

}
