package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

/**
 * TReportTemplateElements generated by hbm2java
 */
public class TReportTemplateElements
    implements java.io.Serializable {

    private TReportTemplateElementsId id;

    public TReportTemplateElements() {
    }

    public TReportTemplateElements(TReportTemplateElementsId id) {
        this.id = id;
    }

    public TReportTemplateElementsId getId() {

        return this.id;
    }

    public void setId(TReportTemplateElementsId id) {

        this.id = id;
    }

}
