package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TReportMain generated by hbm2java
 */
public class TReportMain
    implements java.io.Serializable {

    private int reportId;

    private String reportName;

    private String reportDescription;

    private Date lastModDate;

    private String lastModBy;

    public TReportMain() {
    }

    public TReportMain(int reportId) {
        this.reportId = reportId;
    }

    public TReportMain(int reportId, String reportName,
                       String reportDescription, Date lastModDate,
                       String lastModBy) {
        this.reportId = reportId;
        this.reportName = reportName;
        this.reportDescription = reportDescription;
        this.lastModDate = lastModDate;
        this.lastModBy = lastModBy;
    }

    public int getReportId() {

        return this.reportId;
    }

    public void setReportId(int reportId) {

        this.reportId = reportId;
    }

    public String getReportName() {

        return this.reportName;
    }

    public void setReportName(String reportName) {

        this.reportName = reportName;
    }

    public String getReportDescription() {

        return this.reportDescription;
    }

    public void setReportDescription(String reportDescription) {

        this.reportDescription = reportDescription;
    }

    public Date getLastModDate() {

        return this.lastModDate;
    }

    public void setLastModDate(Date lastModDate) {

        this.lastModDate = lastModDate;
    }

    public String getLastModBy() {

        return this.lastModBy;
    }

    public void setLastModBy(String lastModBy) {

        this.lastModBy = lastModBy;
    }

}
