package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

/**
 * TSecurity generated by hbm2java
 */
public class TSecurity
    implements java.io.Serializable {

    private String securityId;

    private String securityName;

    private String securityIssuerId;

    private Integer securityExposureCount;

    private Integer securityExposureAmount;

    private Byte securityCurrentPrice;

    private Short securityMktCap;

    private String securityType;

    public TSecurity() {
    }

    public TSecurity(String securityId, String securityName,
                     String securityIssuerId, String securityType) {
        this.securityId = securityId;
        this.securityName = securityName;
        this.securityIssuerId = securityIssuerId;
        this.securityType = securityType;
    }

    public TSecurity(String securityId, String securityName,
                     String securityIssuerId, Integer securityExposureCount,
                     Integer securityExposureAmount, Byte securityCurrentPrice,
                     Short securityMktCap, String securityType) {
        this.securityId = securityId;
        this.securityName = securityName;
        this.securityIssuerId = securityIssuerId;
        this.securityExposureCount = securityExposureCount;
        this.securityExposureAmount = securityExposureAmount;
        this.securityCurrentPrice = securityCurrentPrice;
        this.securityMktCap = securityMktCap;
        this.securityType = securityType;
    }

    public String getSecurityId() {

        return this.securityId;
    }

    public void setSecurityId(String securityId) {

        this.securityId = securityId;
    }

    public String getSecurityName() {

        return this.securityName;
    }

    public void setSecurityName(String securityName) {

        this.securityName = securityName;
    }

    public String getSecurityIssuerId() {

        return this.securityIssuerId;
    }

    public void setSecurityIssuerId(String securityIssuerId) {

        this.securityIssuerId = securityIssuerId;
    }

    public Integer getSecurityExposureCount() {

        return this.securityExposureCount;
    }

    public void setSecurityExposureCount(Integer securityExposureCount) {

        this.securityExposureCount = securityExposureCount;
    }

    public Integer getSecurityExposureAmount() {

        return this.securityExposureAmount;
    }

    public void setSecurityExposureAmount(Integer securityExposureAmount) {

        this.securityExposureAmount = securityExposureAmount;
    }

    public Byte getSecurityCurrentPrice() {

        return this.securityCurrentPrice;
    }

    public void setSecurityCurrentPrice(Byte securityCurrentPrice) {

        this.securityCurrentPrice = securityCurrentPrice;
    }

    public Short getSecurityMktCap() {

        return this.securityMktCap;
    }

    public void setSecurityMktCap(Short securityMktCap) {

        this.securityMktCap = securityMktCap;
    }

    public String getSecurityType() {

        return this.securityType;
    }

    public void setSecurityType(String securityType) {

        this.securityType = securityType;
    }

}
