package com.tarun.bootlearn.model.frd_main;
// Generated 08-Jan-2018 14:20:32 by Hibernate Tools 4.3.1.Final

/**
 * TSecurityXreference generated by hbm2java
 */
public class TSecurityXreference
    implements java.io.Serializable {

    private int securityId;

    private String securityXrefType;

    private String securityXrefId;

    public TSecurityXreference() {
    }

    public TSecurityXreference(int securityId) {
        this.securityId = securityId;
    }

    public TSecurityXreference(int securityId, String securityXrefType,
                               String securityXrefId) {
        this.securityId = securityId;
        this.securityXrefType = securityXrefType;
        this.securityXrefId = securityXrefId;
    }

    public int getSecurityId() {

        return this.securityId;
    }

    public void setSecurityId(int securityId) {

        this.securityId = securityId;
    }

    public String getSecurityXrefType() {

        return this.securityXrefType;
    }

    public void setSecurityXrefType(String securityXrefType) {

        this.securityXrefType = securityXrefType;
    }

    public String getSecurityXrefId() {

        return this.securityXrefId;
    }

    public void setSecurityXrefId(String securityXrefId) {

        this.securityXrefId = securityXrefId;
    }

}
